# This file was generated by GoReleaser. DO NOT EDIT.
cask "quantum-cli" do
  version "3.3.0"

  on_macos do
    on_intel do
      sha256 "dd31fcb334a2b9f93dd111c8d6922e22c71c4da8a6aeb929f68a640f856c21ac"
      url "https://github.com/pngmbh/quantum-cli/releases/download/v#{version}/quantum-cli-darwin-amd64"
      binary "quantum-cli-darwin-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "a60063fc66ffbd22413120ddd805d0a58c5a9dabd99a39fd3bad0ee10e28da42"
      url "https://github.com/pngmbh/quantum-cli/releases/download/v#{version}/quantum-cli-darwin-arm64"
      binary "quantum-cli-darwin-arm64", target: "quantum-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "a529f36670394a7fa3c86597c93916d62f440468806f2fd2489160ff452c2338"
      url "https://github.com/pngmbh/quantum-cli/releases/download/v#{version}/quantum-cli-linux-amd64"
      binary "quantum-cli-linux-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "1be92694421bfb7a49d80620bcb865812d4bc4c0d3a428839a1980612e5e4b3b"
      url "https://github.com/pngmbh/quantum-cli/releases/download/v#{version}/quantum-cli-linux-arm64"
      binary "quantum-cli-linux-arm64", target: "quantum-cli"
    end
  end

  name "quantum-cli"
  desc "quantum-cli deploys and manages stacks on Planetary Quantum's Docker platform"
  homepage "https://docs.planetary-quantum.com/setup/quantum-cli-basics/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quantum-cli"]
    end
  end

  # No zap stanza required

end
