# This file was generated by GoReleaser. DO NOT EDIT.
cask "quantum-cli" do
  version "3.3.2"

  on_macos do
    on_intel do
      sha256 "4f3c5a5f8380a83149e16244998c2a9fa96eaed891e42fbc0a422cb89fc55ba3"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-darwin-amd64"
      binary "quantum-cli-darwin-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "82a1062fdf7c02e66368bf850647835b516675c1bda8ff0a76bb77a8a84e4e6c"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-darwin-arm64"
      binary "quantum-cli-darwin-arm64", target: "quantum-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "cabf81a381ed9c718d42dd2baecca7b3160ff16f699500c1cf8f5cb063d0aa24"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-linux-amd64"
      binary "quantum-cli-linux-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "5f32c601a8276595337fdcd02473520b9004da71ad8ffb557c67fa5e8d7d7f20"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-linux-arm64"
      binary "quantum-cli-linux-arm64", target: "quantum-cli"
    end
  end

  name "quantum-cli"
  desc "quantum-cli deploys and manages stacks on Planetary Quantum's Docker platform"
  homepage "https://docs.planetary-quantum.com/setup/quantum-cli-basics/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", *Dir["#{staged_path}/quantum-cli-*"]],
                     sudo: false
    end
  end

  # No zap stanza required

end
