# This file was generated by GoReleaser. DO NOT EDIT.
cask "quantum-cli" do
  version "3.3.1"

  on_macos do
    on_intel do
      sha256 "80194a50bbad6337e32f026a7388f14fcc9aef90bb5136762fe34f5f925bae1a"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-darwin-amd64"
      binary "quantum-cli-darwin-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "cde36f04b66138f2d8917f17f832a40fc3058f273ec3c3a6840dc618a06742f9"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-darwin-arm64"
      binary "quantum-cli-darwin-arm64", target: "quantum-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f2bf01e50c354e0266d9ff9d19894b08cb55442c54e533c6f979f77dc25cb6f"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-linux-amd64"
      binary "quantum-cli-linux-amd64", target: "quantum-cli"
    end
    on_arm do
      sha256 "58e1ef3ace80c333eeceae120f45f8be8cb06a79c95632be887e74763a5cb553"
      url "https://cli-v3.planetary-quantum.com/#{version}/quantum-cli-linux-arm64"
      binary "quantum-cli-linux-arm64", target: "quantum-cli"
    end
  end

  name "quantum-cli"
  desc "quantum-cli deploys and manages stacks on Planetary Quantum's Docker platform"
  homepage "https://docs.planetary-quantum.com/setup/quantum-cli-basics/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quantum-cli"]
    end
  end

  # No zap stanza required

end
