# This file was generated by GoReleaser. DO NOT EDIT.
cask "runway" do
  version "1.47.0"

  on_macos do
    on_intel do
      sha256 "b0b732e699a4cb4bc8b5ee10b8bb42e9f6e0038ff7e4d662b125dbc4a281d59a"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_x86_64.tar.gz"
      rename "runway_Darwin_x86_64/runway", "runway"
    end
    on_arm do
      sha256 "adf94143a0d366bd705f7e6d02ed3a33d0315c5845e161a6d9fe9875c3a2599e"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_arm64.tar.gz"
      rename "runway_Darwin_arm64/runway", "runway"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ee88189b4a9715c364b3ad95d541ffcfbf5366fe446c0bdf57fc3455ccd8ed1"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_x86_64.tar.gz"
      rename "runway_Linux_x86_64/runway", "runway"
    end
    on_arm do
      sha256 "ec942986d946e2d0e366b8021f6d8a5f78a1d40ec6a3c168133f9d1d360e8114"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_arm64.tar.gz"
      rename "runway_Linux_arm64/runway", "runway"
    end
  end

  name "runway"
  desc "Runway CLI to deploy and manage apps on the Runway PaaS"
  homepage "https://www.runway.horse/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", *Dir["#{staged_path}/**/runway"]],
                     sudo: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `runway login` to get started, and `runway install-completions` to install auto-complete
  EOS
end
