# This file was generated by GoReleaser. DO NOT EDIT.
cask "runway" do
  version "1.47.1"

  on_macos do
    on_arm do
      sha256 "a1462a8acdbf2fe705b4712ef9ab27d8ba55c69a04369b1a0f6c235e9769580d"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_arm64.tar.gz"
      rename "runway_Darwin_arm64/runway", "runway"
    end
    on_intel do
      sha256 "4fcaaad6a6b3772c226d33d62bf37e1970e40036f10cc06bd8a582816501553b"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_x86_64.tar.gz"
      rename "runway_Darwin_x86_64/runway", "runway"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ddb8ebd30f614ce99e0d244d8a160ec2aec3a9cdba9579d5ab9d593e4774450"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_arm64.tar.gz"
      rename "runway_Linux_arm64/runway", "runway"
    end
    on_intel do
      sha256 "d98f9acfde1c023b1ec6574e8e259d2bc05b6e9b982c7d538d8b21666a04d84e"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_x86_64.tar.gz"
      rename "runway_Linux_x86_64/runway", "runway"
    end
  end

  name "runway"
  desc "Runway CLI to deploy and manage apps on the Runway PaaS"
  homepage "https://www.runway.horse/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", *Dir["#{staged_path}/**/runway"]],
                     sudo: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `runway login` to get started, and `runway install-completions` to install auto-complete
  EOS
end
