# This file was generated by GoReleaser. DO NOT EDIT.
cask "runway" do
  version "1.48.0"

  on_macos do
    on_arm do
      sha256 "4272d68d61a9d1055ac3e6e1524c0ac9ec02dad2d1393d5611c2eb4afae35355"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_arm64.tar.gz"
      rename "runway_Darwin_arm64/runway", "runway"
    end
    on_intel do
      sha256 "a9d3c4b55a4102ef01b1df770d96b1a47c6ca9a501dcc172bfe4f241dbc94a82"
      url "https://download.runway.horse/runway/#{version}/runway_Darwin_x86_64.tar.gz"
      rename "runway_Darwin_x86_64/runway", "runway"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb6e59b572aaeea859292f36842be9df30f3d84e31eb05f839482ce3385eed85"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_arm64.tar.gz"
      rename "runway_Linux_arm64/runway", "runway"
    end
    on_intel do
      sha256 "feb16e818801e0c5eb29851e3f5771cc97b06726ddf9a1ea9eae6c5d64c0af28"
      url "https://download.runway.horse/runway/#{version}/runway_Linux_x86_64.tar.gz"
      rename "runway_Linux_x86_64/runway", "runway"
    end
  end

  name "runway"
  desc "Runway CLI to deploy and manage apps on the Runway PaaS"
  homepage "https://www.runway.horse/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", *Dir["#{staged_path}/**/runway"]],
                     sudo: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `runway login` to get started, and `runway install-completions` to install auto-complete
  EOS
end
